version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - pip3 install --upgrade awscli
      - pip3 install --upgrade aws-sam-cli
      - sam --version

  pre_build:
    commands:
      - cd NOOP
      - mvn clean install
      - echo PlateDetected NOOP\:\ Build completed on `date`
      - cd ../PlateDetected/
      - mvn clean install
      - echo PlateDetected \:\ Build completed on `date`

  build:
    commands:
      - cd ..
      - sam build
      - echo PlateDetected\:\ SAM build completed on `date`
  
  post_build:
    commands:
      - sam package --s3-bucket $BUILD_OUTPUT_BUCKET --output-template-file template-export.yml
      - echo PlateDetected\:\ SAM packaging completed on `date`

artifacts:
  type: zip
  files:
    - template-export.yml
