version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - pip3 install --upgrade awscli
      - pip3 install --upgrade aws-sam-cli
      - sam --version

  pre_build:
    commands:
      - cd activitypoller
      - mvn clean install
      - echo ActivityPoller\:\ Build completed on `date`

  build:
    commands:
      - cd ..
      - sam build
      - echo ActivityPoller\:\ SAM build completed on `date`
  
  post_build:
    commands:
      - sam package --s3-bucket $BUILD_OUTPUT_BUCKET --output-template-file template-export.yml
      - echo ActivityPoller\:\ SAM packaging completed on `date`

cache:
  paths:
    - '/root/.m2/**/*'
artifacts:
  type: zip
  files:
    - template-export.yml